apiVersion: v1
kind: Service
metadata:
  name: guestbook
  namespace: web-tier
  labels:
    app: guestbook
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: guestbook
  type: LoadBalancer
